/**
 * Style Dictionary Configuration - Phase 4
 *
 * DTCG is source of truth, CSS is generated artifact.
 *
 * Architecture Decision (SYOS-434):
 * - Phase 4 (Current): DTCG becomes source of truth
 *   - Style Dictionary reads design-system.json (DTCG format)
 *   - Style Dictionary generates CSS from DTCG
 *   - CSS becomes generated artifact
 *
 * Usage:
 *   npm run tokens:build            # Generate CSS from DTCG
 *   npm run tokens:validate        # Validates CSS tokens
 *   npm run tokens:validate-dtcg   # Validates DTCG format
 */

import StyleDictionary from 'style-dictionary';
import { convertDTCGToSD } from './scripts/style-dictionary/prepare-tokens.js';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Pre-process DTCG to Style Dictionary format
const dtcgPath = path.join(__dirname, 'design-system.json');
const tokensPath = path.join(__dirname, 'tokens.json');

// Convert DTCG to SD format before Style Dictionary runs
if (fs.existsSync(dtcgPath)) {
	convertDTCGToSD(dtcgPath, tokensPath);
}

import {
	transformTailwindTheme,
	transformTailwindUtility,
	transformValidateSemanticReference
} from './scripts/style-dictionary/transforms.js';

// Register custom transforms
StyleDictionary.registerTransform({
	name: 'tailwind/theme',
	type: 'value',
	transitive: false,
	transform: transformTailwindTheme
});

StyleDictionary.registerTransform({
	name: 'tailwind/utility',
	type: 'value',
	transitive: false,
	transform: transformTailwindUtility
});

StyleDictionary.registerTransform({
	name: 'validate/semantic-reference',
	type: 'value',
	transitive: false,
	transform: transformValidateSemanticReference
});

// Register custom format for @theme blocks
StyleDictionary.registerFormat({
	name: 'tailwind/theme',
	format: ({ dictionary }) => {
		const tokens = dictionary.allTokens
			.map((token) => transformTailwindTheme(token))
			.filter(Boolean)
			.join('\n');

		const header = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * 
 * This file is automatically generated from design-system.json (DTCG format).
 * To modify tokens, edit design-system.json and run: npm run tokens:build
 * 
 * Generated: ${new Date().toISOString()}
 */
`;

		return `${header}@theme {\n${tokens}\n}`;
	}
});

// Register custom format for @utility blocks
StyleDictionary.registerFormat({
	name: 'tailwind/utility',
	format: ({ dictionary }) => {
		const utilities = dictionary.allTokens
			.map((token) => transformTailwindUtility(token))
			.filter(Boolean)
			.join('\n\n');

		const header = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * 
 * This file is automatically generated from design-system.json (DTCG format).
 * To modify tokens, edit design-system.json and run: npm run tokens:build
 * 
 * Generated: ${new Date().toISOString()}
 */
`;

		return `${header}${utilities}`;
	}
});

export default {
	// Source: Pre-processed tokens (converted from DTCG)
	source: ['tokens.json'],

	// Platforms: Generate CSS files
	platforms: {
		css: {
			transformGroup: 'css',
			buildPath: 'src/styles/tokens/',
			files: [
				{
					destination: 'spacing.css',
					format: 'tailwind/theme',
					filter: (token) => token.path[0] === 'spacing'
				},
				{
					destination: 'colors.css',
					format: 'tailwind/theme',
					filter: (token) => token.path[0] === 'color'
				},
				{
					destination: 'typography.css',
					format: 'tailwind/theme',
					filter: (token) => token.path[0] === 'typography'
				},
				{
					destination: 'effects.css',
					format: 'tailwind/theme',
					filter: (token) =>
						token.path[0] === 'shadow' ||
						token.path[0] === 'borderRadius' ||
						token.path[0] === 'transition' ||
						token.path[0] === 'zIndex'
				},
				{
					destination: 'sizes.css',
					format: 'tailwind/theme',
					filter: (token) => token.path[0] === 'size'
				}
			]
		},
		utilities: {
			transformGroup: 'css',
			buildPath: 'src/styles/utilities/',
			files: [
				{
					destination: 'spacing-utils.css',
					format: 'tailwind/utility',
					filter: (token) => token.path[0] === 'spacing'
				},
				{
					destination: 'color-utils.css',
					format: 'tailwind/utility',
					filter: (token) => token.path[0] === 'color'
				},
				{
					destination: 'typography-utils.css',
					format: 'tailwind/utility',
					filter: (token) => token.path[0] === 'typography'
				},
				{
					destination: 'component-utils.css',
					format: 'tailwind/utility',
					filter: (token) =>
						token.path[0] === 'shadow' ||
						token.path[0] === 'borderRadius' ||
						token.path[0] === 'size'
				}
			]
		}
	}
};
