/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as admin_invariants from "../admin/invariants.js";
import type * as admin_invariants_assignments from "../admin/invariants/assignments.js";
import type * as admin_invariants_authority from "../admin/invariants/authority.js";
import type * as admin_invariants_circleMembership from "../admin/invariants/circleMembership.js";
import type * as admin_invariants_crossDomain from "../admin/invariants/crossDomain.js";
import type * as admin_invariants_governance from "../admin/invariants/governance.js";
import type * as admin_invariants_history from "../admin/invariants/history.js";
import type * as admin_invariants_identity from "../admin/invariants/identity.js";
import type * as admin_invariants_index from "../admin/invariants/index.js";
import type * as admin_invariants_organization from "../admin/invariants/organization.js";
import type * as admin_invariants_proposals from "../admin/invariants/proposals.js";
import type * as admin_invariants_roles from "../admin/invariants/roles.js";
import type * as admin_invariants_types from "../admin/invariants/types.js";
import type * as admin_invariants_workspaces from "../admin/invariants/workspaces.js";
import type * as admin_migrations_migrateCircleItemsToCustomFields from "../admin/migrations/migrateCircleItemsToCustomFields.js";
import type * as admin_migrations_migrateProjectsToPersonId from "../admin/migrations/migrateProjectsToPersonId.js";
import type * as admin_migrations_migrateTasksAuditFields from "../admin/migrations/migrateTasksAuditFields.js";
import type * as admin_orgStructureImport from "../admin/orgStructureImport.js";
import type * as admin_rbac from "../admin/rbac.js";
import type * as admin_resetWorkspace from "../admin/resetWorkspace.js";
import type * as admin_seed_bootstrap from "../admin/seed/bootstrap.js";
import type * as admin_seed_customFieldDefinitions from "../admin/seed/customFieldDefinitions.js";
import type * as admin_seed_index from "../admin/seed/index.js";
import type * as admin_seed_meetingTemplates from "../admin/seed/meetingTemplates.js";
import type * as admin_seed_roleTemplates from "../admin/seed/roleTemplates.js";
import type * as admin_seed_workspaceSeed from "../admin/seed/workspaceSeed.js";
import type * as admin_settings from "../admin/settings.js";
import type * as admin_users from "../admin/users.js";
import type * as core_assignments_index from "../core/assignments/index.js";
import type * as core_assignments_mutations from "../core/assignments/mutations.js";
import type * as core_assignments_queries from "../core/assignments/queries.js";
import type * as core_assignments_rules from "../core/assignments/rules.js";
import type * as core_assignments_tables from "../core/assignments/tables.js";
import type * as core_authority_calculator from "../core/authority/calculator.js";
import type * as core_authority_context from "../core/authority/context.js";
import type * as core_authority_index from "../core/authority/index.js";
import type * as core_authority_mutations from "../core/authority/mutations.js";
import type * as core_authority_policies from "../core/authority/policies.js";
import type * as core_authority_queries from "../core/authority/queries.js";
import type * as core_authority_quickEdit from "../core/authority/quickEdit.js";
import type * as core_authority_rules from "../core/authority/rules.js";
import type * as core_authority_types from "../core/authority/types.js";
import type * as core_circles_autoCreateRoles from "../core/circles/autoCreateRoles.js";
import type * as core_circles_circleAccess from "../core/circles/circleAccess.js";
import type * as core_circles_circleArchival from "../core/circles/circleArchival.js";
import type * as core_circles_circleLifecycle from "../core/circles/circleLifecycle.js";
import type * as core_circles_circleList from "../core/circles/circleList.js";
import type * as core_circles_circleMembers from "../core/circles/circleMembers.js";
import type * as core_circles_constants from "../core/circles/constants.js";
import type * as core_circles_index from "../core/circles/index.js";
import type * as core_circles_mutations from "../core/circles/mutations.js";
import type * as core_circles_queries from "../core/circles/queries.js";
import type * as core_circles_rules from "../core/circles/rules.js";
import type * as core_circles_slug from "../core/circles/slug.js";
import type * as core_circles_tables from "../core/circles/tables.js";
import type * as core_circles_triggers from "../core/circles/triggers.js";
import type * as core_circles_validation from "../core/circles/validation.js";
import type * as core_history_capture from "../core/history/capture.js";
import type * as core_history_index from "../core/history/index.js";
import type * as core_history_queries from "../core/history/queries.js";
import type * as core_history_types from "../core/history/types.js";
import type * as core_index from "../core/index.js";
import type * as core_people_constants from "../core/people/constants.js";
import type * as core_people_index from "../core/people/index.js";
import type * as core_people_mutations from "../core/people/mutations.js";
import type * as core_people_queries from "../core/people/queries.js";
import type * as core_people_rules from "../core/people/rules.js";
import type * as core_people_tables from "../core/people/tables.js";
import type * as core_policies_index from "../core/policies/index.js";
import type * as core_policies_mutations from "../core/policies/mutations.js";
import type * as core_policies_queries from "../core/policies/queries.js";
import type * as core_policies_rules from "../core/policies/rules.js";
import type * as core_proposals_constants from "../core/proposals/constants.js";
import type * as core_proposals_index from "../core/proposals/index.js";
import type * as core_proposals_mutations from "../core/proposals/mutations.js";
import type * as core_proposals_notifications from "../core/proposals/notifications.js";
import type * as core_proposals_queries from "../core/proposals/queries.js";
import type * as core_proposals_rules from "../core/proposals/rules.js";
import type * as core_proposals_tables from "../core/proposals/tables.js";
import type * as core_roles_constants from "../core/roles/constants.js";
import type * as core_roles_index from "../core/roles/index.js";
import type * as core_roles_mutations from "../core/roles/mutations.js";
import type * as core_roles_queries from "../core/roles/queries.js";
import type * as core_roles_roleAccess from "../core/roles/roleAccess.js";
import type * as core_roles_roleRbac from "../core/roles/roleRbac.js";
import type * as core_roles_rules from "../core/roles/rules.js";
import type * as core_roles_tables from "../core/roles/tables.js";
import type * as core_roles_templates_index from "../core/roles/templates/index.js";
import type * as core_roles_templates_mutations from "../core/roles/templates/mutations.js";
import type * as core_roles_templates_queries from "../core/roles/templates/queries.js";
import type * as core_roles_templates_rules from "../core/roles/templates/rules.js";
import type * as core_users_constants from "../core/users/constants.js";
import type * as core_users_index from "../core/users/index.js";
import type * as core_users_mutations from "../core/users/mutations.js";
import type * as core_users_queries from "../core/users/queries.js";
import type * as core_users_rules from "../core/users/rules.js";
import type * as core_users_tables from "../core/users/tables.js";
import type * as core_workspaces_access from "../core/workspaces/access.js";
import type * as core_workspaces_index from "../core/workspaces/index.js";
import type * as core_workspaces_lifecycle from "../core/workspaces/lifecycle.js";
import type * as core_workspaces_members from "../core/workspaces/members.js";
import type * as core_workspaces_mutations from "../core/workspaces/mutations.js";
import type * as core_workspaces_queries from "../core/workspaces/queries.js";
import type * as core_workspaces_rules from "../core/workspaces/rules.js";
import type * as core_workspaces_settings from "../core/workspaces/settings.js";
import type * as core_workspaces_tables from "../core/workspaces/tables.js";
import type * as docs_doc404Tracking from "../docs/doc404Tracking.js";
import type * as features_customFields_constants from "../features/customFields/constants.js";
import type * as features_customFields_index from "../features/customFields/index.js";
import type * as features_customFields_mutations from "../features/customFields/mutations.js";
import type * as features_customFields_queries from "../features/customFields/queries.js";
import type * as features_customFields_rules from "../features/customFields/rules.js";
import type * as features_customFields_tables from "../features/customFields/tables.js";
import type * as features_export_blog from "../features/export/blog.js";
import type * as features_export_index from "../features/export/index.js";
import type * as features_flashcards_auth from "../features/flashcards/auth.js";
import type * as features_flashcards_creation from "../features/flashcards/creation.js";
import type * as features_flashcards_importExport from "../features/flashcards/importExport.js";
import type * as features_flashcards_importFlashcards from "../features/flashcards/importFlashcards.js";
import type * as features_flashcards_index from "../features/flashcards/index.js";
import type * as features_flashcards_lifecycle from "../features/flashcards/lifecycle.js";
import type * as features_flashcards_lookups from "../features/flashcards/lookups.js";
import type * as features_flashcards_queries from "../features/flashcards/queries.js";
import type * as features_flashcards_repository from "../features/flashcards/repository.js";
import type * as features_flashcards_review from "../features/flashcards/review.js";
import type * as features_flashcards_reviewSchedule from "../features/flashcards/reviewSchedule.js";
import type * as features_flashcards_settings from "../features/flashcards/settings.js";
import type * as features_flashcards_state from "../features/flashcards/state.js";
import type * as features_flashcards_stats from "../features/flashcards/stats.js";
import type * as features_flashcards_tables from "../features/flashcards/tables.js";
import type * as features_flashcards_tags from "../features/flashcards/tags.js";
import type * as features_inbox_access from "../features/inbox/access.js";
import type * as features_inbox_assignments from "../features/inbox/assignments.js";
import type * as features_inbox_index from "../features/inbox/index.js";
import type * as features_inbox_lifecycle from "../features/inbox/lifecycle.js";
import type * as features_inbox_notifications from "../features/inbox/notifications.js";
import type * as features_inbox_queries from "../features/inbox/queries.js";
import type * as features_inbox_tables from "../features/inbox/tables.js";
import type * as features_invites_helpers from "../features/invites/helpers.js";
import type * as features_invites_index from "../features/invites/index.js";
import type * as features_invites_mutations from "../features/invites/mutations.js";
import type * as features_invites_queries from "../features/invites/queries.js";
import type * as features_invites_rules from "../features/invites/rules.js";
import type * as features_invites_tables from "../features/invites/tables.js";
import type * as features_meetings_agendaItems from "../features/meetings/agendaItems.js";
import type * as features_meetings_helpers_access from "../features/meetings/helpers/access.js";
import type * as features_meetings_helpers_invitations from "../features/meetings/helpers/invitations.js";
import type * as features_meetings_helpers_invitations_index from "../features/meetings/helpers/invitations/index.js";
import type * as features_meetings_helpers_invitations_mutations from "../features/meetings/helpers/invitations/mutations.js";
import type * as features_meetings_helpers_invitations_queries from "../features/meetings/helpers/invitations/queries.js";
import type * as features_meetings_helpers_meetingMutations from "../features/meetings/helpers/meetingMutations.js";
import type * as features_meetings_helpers_meetingQueries from "../features/meetings/helpers/meetingQueries.js";
import type * as features_meetings_helpers_mutations_agendaItems from "../features/meetings/helpers/mutations/agendaItems.js";
import type * as features_meetings_helpers_mutations_archive from "../features/meetings/helpers/mutations/archive.js";
import type * as features_meetings_helpers_mutations_attendees from "../features/meetings/helpers/mutations/attendees.js";
import type * as features_meetings_helpers_mutations_createUpdate from "../features/meetings/helpers/mutations/createUpdate.js";
import type * as features_meetings_helpers_mutations_index from "../features/meetings/helpers/mutations/index.js";
import type * as features_meetings_helpers_mutations_lifecycle from "../features/meetings/helpers/mutations/lifecycle.js";
import type * as features_meetings_helpers_mutations_session from "../features/meetings/helpers/mutations/session.js";
import type * as features_meetings_helpers_queries_agendaItems from "../features/meetings/helpers/queries/agendaItems.js";
import type * as features_meetings_helpers_queries_get from "../features/meetings/helpers/queries/get.js";
import type * as features_meetings_helpers_queries_index from "../features/meetings/helpers/queries/index.js";
import type * as features_meetings_helpers_queries_invitedUsers from "../features/meetings/helpers/queries/invitedUsers.js";
import type * as features_meetings_helpers_queries_invitedUsersUtils from "../features/meetings/helpers/queries/invitedUsersUtils.js";
import type * as features_meetings_helpers_queries_list from "../features/meetings/helpers/queries/list.js";
import type * as features_meetings_helpers_queries_listByCircle from "../features/meetings/helpers/queries/listByCircle.js";
import type * as features_meetings_helpers_queries_listByTemplate from "../features/meetings/helpers/queries/listByTemplate.js";
import type * as features_meetings_helpers_queries_listForUser from "../features/meetings/helpers/queries/listForUser.js";
import type * as features_meetings_helpers_queries_shared from "../features/meetings/helpers/queries/shared.js";
import type * as features_meetings_helpers_templates from "../features/meetings/helpers/templates.js";
import type * as features_meetings_helpers_templates_index from "../features/meetings/helpers/templates/index.js";
import type * as features_meetings_helpers_templates_mutations from "../features/meetings/helpers/templates/mutations.js";
import type * as features_meetings_helpers_templates_queries from "../features/meetings/helpers/templates/queries.js";
import type * as features_meetings_helpers_templates_steps from "../features/meetings/helpers/templates/steps.js";
import type * as features_meetings_index from "../features/meetings/index.js";
import type * as features_meetings_invitations from "../features/meetings/invitations.js";
import type * as features_meetings_meetings from "../features/meetings/meetings.js";
import type * as features_meetings_presence from "../features/meetings/presence.js";
import type * as features_meetings_tables from "../features/meetings/tables.js";
import type * as features_meetings_templates from "../features/meetings/templates.js";
import type * as features_notes_index from "../features/notes/index.js";
import type * as features_onboarding_index from "../features/onboarding/index.js";
import type * as features_onboarding_mutations from "../features/onboarding/mutations.js";
import type * as features_onboarding_queries from "../features/onboarding/queries.js";
import type * as features_onboarding_rules from "../features/onboarding/rules.js";
import type * as features_onboarding_tables from "../features/onboarding/tables.js";
import type * as features_projects_index from "../features/projects/index.js";
import type * as features_projects_tables from "../features/projects/tables.js";
import type * as features_readwise_access from "../features/readwise/access.js";
import type * as features_readwise_api from "../features/readwise/api.js";
import type * as features_readwise_cleanup from "../features/readwise/cleanup.js";
import type * as features_readwise_fetch from "../features/readwise/fetch.js";
import type * as features_readwise_filters from "../features/readwise/filters.js";
import type * as features_readwise_highlights from "../features/readwise/highlights.js";
import type * as features_readwise_index from "../features/readwise/index.js";
import type * as features_readwise_jobs from "../features/readwise/jobs.js";
import type * as features_readwise_mutations from "../features/readwise/mutations.js";
import type * as features_readwise_mutations_authorsSources from "../features/readwise/mutations/authorsSources.js";
import type * as features_readwise_mutations_highlights from "../features/readwise/mutations/highlights.js";
import type * as features_readwise_mutations_index from "../features/readwise/mutations/index.js";
import type * as features_readwise_mutations_progress from "../features/readwise/mutations/progress.js";
import type * as features_readwise_mutations_queries from "../features/readwise/mutations/queries.js";
import type * as features_readwise_mutations_tags from "../features/readwise/mutations/tags.js";
import type * as features_readwise_orchestrator from "../features/readwise/orchestrator.js";
import type * as features_readwise_persistence from "../features/readwise/persistence.js";
import type * as features_readwise_progress from "../features/readwise/progress.js";
import type * as features_readwise_queries_progress from "../features/readwise/queries/progress.js";
import type * as features_readwise_sources from "../features/readwise/sources.js";
import type * as features_readwise_sync from "../features/readwise/sync.js";
import type * as features_readwise_tables from "../features/readwise/tables.js";
import type * as features_readwise_testApi from "../features/readwise/testApi.js";
import type * as features_readwise_transform from "../features/readwise/transform.js";
import type * as features_readwise_utils from "../features/readwise/utils.js";
import type * as features_tags_access from "../features/tags/access.js";
import type * as features_tags_assignments from "../features/tags/assignments.js";
import type * as features_tags_hierarchy from "../features/tags/hierarchy.js";
import type * as features_tags_index from "../features/tags/index.js";
import type * as features_tags_lifecycle from "../features/tags/lifecycle.js";
import type * as features_tags_queries from "../features/tags/queries.js";
import type * as features_tags_tables from "../features/tags/tables.js";
import type * as features_tags_types from "../features/tags/types.js";
import type * as features_tags_validation from "../features/tags/validation.js";
import type * as features_tasks_access from "../features/tasks/access.js";
import type * as features_tasks_assignments from "../features/tasks/assignments.js";
import type * as features_tasks_index from "../features/tasks/index.js";
import type * as features_tasks_lifecycle from "../features/tasks/lifecycle.js";
import type * as features_tasks_mutations from "../features/tasks/mutations.js";
import type * as features_tasks_queries from "../features/tasks/queries.js";
import type * as features_tasks_tables from "../features/tasks/tables.js";
import type * as features_tasks_types from "../features/tasks/types.js";
import type * as features_waitlist_index from "../features/waitlist/index.js";
import type * as features_workspaceBranding_index from "../features/workspaceBranding/index.js";
import type * as features_workspaceSettings_index from "../features/workspaceSettings/index.js";
import type * as features_workspaces_index from "../features/workspaces/index.js";
import type * as features_workspaces_members from "../features/workspaces/members.js";
import type * as http from "../http.js";
import type * as infrastructure_access_permissions from "../infrastructure/access/permissions.js";
import type * as infrastructure_access_withCircleAccess from "../infrastructure/access/withCircleAccess.js";
import type * as infrastructure_access_workspaceRoles from "../infrastructure/access/workspaceRoles.js";
import type * as infrastructure_auth from "../infrastructure/auth.js";
import type * as infrastructure_auth_helpers from "../infrastructure/auth/helpers.js";
import type * as infrastructure_auth_tables from "../infrastructure/auth/tables.js";
import type * as infrastructure_auth_validateApiKeys from "../infrastructure/auth/validateApiKeys.js";
import type * as infrastructure_auth_verification from "../infrastructure/auth/verification.js";
import type * as infrastructure_authSessions from "../infrastructure/authSessions.js";
import type * as infrastructure_crypto from "../infrastructure/crypto.js";
import type * as infrastructure_customFields_helpers from "../infrastructure/customFields/helpers.js";
import type * as infrastructure_customFields_index from "../infrastructure/customFields/index.js";
import type * as infrastructure_db_withActiveFilter from "../infrastructure/db/withActiveFilter.js";
import type * as infrastructure_email from "../infrastructure/email.js";
import type * as infrastructure_errors_codes from "../infrastructure/errors/codes.js";
import type * as infrastructure_featureFlags from "../infrastructure/featureFlags.js";
import type * as infrastructure_featureFlags_access from "../infrastructure/featureFlags/access.js";
import type * as infrastructure_featureFlags_debug from "../infrastructure/featureFlags/debug.js";
import type * as infrastructure_featureFlags_impact from "../infrastructure/featureFlags/impact.js";
import type * as infrastructure_featureFlags_lifecycle from "../infrastructure/featureFlags/lifecycle.js";
import type * as infrastructure_featureFlags_queries from "../infrastructure/featureFlags/queries.js";
import type * as infrastructure_featureFlags_store from "../infrastructure/featureFlags/store.js";
import type * as infrastructure_featureFlags_targeting from "../infrastructure/featureFlags/targeting.js";
import type * as infrastructure_featureFlags_types from "../infrastructure/featureFlags/types.js";
import type * as infrastructure_featureFlags_utils from "../infrastructure/featureFlags/utils.js";
import type * as infrastructure_featureFlags_validation from "../infrastructure/featureFlags/validation.js";
import type * as infrastructure_http from "../infrastructure/http.js";
import type * as infrastructure_posthog from "../infrastructure/posthog.js";
import type * as infrastructure_rbac_permissions from "../infrastructure/rbac/permissions.js";
import type * as infrastructure_rbac_permissions_access from "../infrastructure/rbac/permissions/access.js";
import type * as infrastructure_rbac_permissions_lifecycle from "../infrastructure/rbac/permissions/lifecycle.js";
import type * as infrastructure_rbac_permissions_logging from "../infrastructure/rbac/permissions/logging.js";
import type * as infrastructure_rbac_permissions_queries from "../infrastructure/rbac/permissions/queries.js";
import type * as infrastructure_rbac_permissions_types from "../infrastructure/rbac/permissions/types.js";
import type * as infrastructure_rbac_permissions_validation from "../infrastructure/rbac/permissions/validation.js";
import type * as infrastructure_rbac_queries from "../infrastructure/rbac/queries.js";
import type * as infrastructure_rbac_roles from "../infrastructure/rbac/roles.js";
import type * as infrastructure_rbac_scopeHelpers from "../infrastructure/rbac/scopeHelpers.js";
import type * as infrastructure_rbac_seedRBAC from "../infrastructure/rbac/seedRBAC.js";
import type * as infrastructure_rbac_setupAdmin from "../infrastructure/rbac/setupAdmin.js";
import type * as infrastructure_rbac_tables from "../infrastructure/rbac/tables.js";
import type * as infrastructure_sessionValidation from "../infrastructure/sessionValidation.js";
import type * as infrastructure_tables from "../infrastructure/tables.js";
import type * as infrastructure_types_prosemirror from "../infrastructure/types/prosemirror.js";
import type * as infrastructure_urls from "../infrastructure/urls.js";
import type * as migrations_clearPeopleEmailDenormalization from "../migrations/clearPeopleEmailDenormalization.js";
import type * as prompts_flashcardGeneration from "../prompts/flashcardGeneration.js";
import type * as prompts_utils from "../prompts/utils.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "admin/invariants": typeof admin_invariants;
  "admin/invariants/assignments": typeof admin_invariants_assignments;
  "admin/invariants/authority": typeof admin_invariants_authority;
  "admin/invariants/circleMembership": typeof admin_invariants_circleMembership;
  "admin/invariants/crossDomain": typeof admin_invariants_crossDomain;
  "admin/invariants/governance": typeof admin_invariants_governance;
  "admin/invariants/history": typeof admin_invariants_history;
  "admin/invariants/identity": typeof admin_invariants_identity;
  "admin/invariants/index": typeof admin_invariants_index;
  "admin/invariants/organization": typeof admin_invariants_organization;
  "admin/invariants/proposals": typeof admin_invariants_proposals;
  "admin/invariants/roles": typeof admin_invariants_roles;
  "admin/invariants/types": typeof admin_invariants_types;
  "admin/invariants/workspaces": typeof admin_invariants_workspaces;
  "admin/migrations/migrateCircleItemsToCustomFields": typeof admin_migrations_migrateCircleItemsToCustomFields;
  "admin/migrations/migrateProjectsToPersonId": typeof admin_migrations_migrateProjectsToPersonId;
  "admin/migrations/migrateTasksAuditFields": typeof admin_migrations_migrateTasksAuditFields;
  "admin/orgStructureImport": typeof admin_orgStructureImport;
  "admin/rbac": typeof admin_rbac;
  "admin/resetWorkspace": typeof admin_resetWorkspace;
  "admin/seed/bootstrap": typeof admin_seed_bootstrap;
  "admin/seed/customFieldDefinitions": typeof admin_seed_customFieldDefinitions;
  "admin/seed/index": typeof admin_seed_index;
  "admin/seed/meetingTemplates": typeof admin_seed_meetingTemplates;
  "admin/seed/roleTemplates": typeof admin_seed_roleTemplates;
  "admin/seed/workspaceSeed": typeof admin_seed_workspaceSeed;
  "admin/settings": typeof admin_settings;
  "admin/users": typeof admin_users;
  "core/assignments/index": typeof core_assignments_index;
  "core/assignments/mutations": typeof core_assignments_mutations;
  "core/assignments/queries": typeof core_assignments_queries;
  "core/assignments/rules": typeof core_assignments_rules;
  "core/assignments/tables": typeof core_assignments_tables;
  "core/authority/calculator": typeof core_authority_calculator;
  "core/authority/context": typeof core_authority_context;
  "core/authority/index": typeof core_authority_index;
  "core/authority/mutations": typeof core_authority_mutations;
  "core/authority/policies": typeof core_authority_policies;
  "core/authority/queries": typeof core_authority_queries;
  "core/authority/quickEdit": typeof core_authority_quickEdit;
  "core/authority/rules": typeof core_authority_rules;
  "core/authority/types": typeof core_authority_types;
  "core/circles/autoCreateRoles": typeof core_circles_autoCreateRoles;
  "core/circles/circleAccess": typeof core_circles_circleAccess;
  "core/circles/circleArchival": typeof core_circles_circleArchival;
  "core/circles/circleLifecycle": typeof core_circles_circleLifecycle;
  "core/circles/circleList": typeof core_circles_circleList;
  "core/circles/circleMembers": typeof core_circles_circleMembers;
  "core/circles/constants": typeof core_circles_constants;
  "core/circles/index": typeof core_circles_index;
  "core/circles/mutations": typeof core_circles_mutations;
  "core/circles/queries": typeof core_circles_queries;
  "core/circles/rules": typeof core_circles_rules;
  "core/circles/slug": typeof core_circles_slug;
  "core/circles/tables": typeof core_circles_tables;
  "core/circles/triggers": typeof core_circles_triggers;
  "core/circles/validation": typeof core_circles_validation;
  "core/history/capture": typeof core_history_capture;
  "core/history/index": typeof core_history_index;
  "core/history/queries": typeof core_history_queries;
  "core/history/types": typeof core_history_types;
  "core/index": typeof core_index;
  "core/people/constants": typeof core_people_constants;
  "core/people/index": typeof core_people_index;
  "core/people/mutations": typeof core_people_mutations;
  "core/people/queries": typeof core_people_queries;
  "core/people/rules": typeof core_people_rules;
  "core/people/tables": typeof core_people_tables;
  "core/policies/index": typeof core_policies_index;
  "core/policies/mutations": typeof core_policies_mutations;
  "core/policies/queries": typeof core_policies_queries;
  "core/policies/rules": typeof core_policies_rules;
  "core/proposals/constants": typeof core_proposals_constants;
  "core/proposals/index": typeof core_proposals_index;
  "core/proposals/mutations": typeof core_proposals_mutations;
  "core/proposals/notifications": typeof core_proposals_notifications;
  "core/proposals/queries": typeof core_proposals_queries;
  "core/proposals/rules": typeof core_proposals_rules;
  "core/proposals/tables": typeof core_proposals_tables;
  "core/roles/constants": typeof core_roles_constants;
  "core/roles/index": typeof core_roles_index;
  "core/roles/mutations": typeof core_roles_mutations;
  "core/roles/queries": typeof core_roles_queries;
  "core/roles/roleAccess": typeof core_roles_roleAccess;
  "core/roles/roleRbac": typeof core_roles_roleRbac;
  "core/roles/rules": typeof core_roles_rules;
  "core/roles/tables": typeof core_roles_tables;
  "core/roles/templates/index": typeof core_roles_templates_index;
  "core/roles/templates/mutations": typeof core_roles_templates_mutations;
  "core/roles/templates/queries": typeof core_roles_templates_queries;
  "core/roles/templates/rules": typeof core_roles_templates_rules;
  "core/users/constants": typeof core_users_constants;
  "core/users/index": typeof core_users_index;
  "core/users/mutations": typeof core_users_mutations;
  "core/users/queries": typeof core_users_queries;
  "core/users/rules": typeof core_users_rules;
  "core/users/tables": typeof core_users_tables;
  "core/workspaces/access": typeof core_workspaces_access;
  "core/workspaces/index": typeof core_workspaces_index;
  "core/workspaces/lifecycle": typeof core_workspaces_lifecycle;
  "core/workspaces/members": typeof core_workspaces_members;
  "core/workspaces/mutations": typeof core_workspaces_mutations;
  "core/workspaces/queries": typeof core_workspaces_queries;
  "core/workspaces/rules": typeof core_workspaces_rules;
  "core/workspaces/settings": typeof core_workspaces_settings;
  "core/workspaces/tables": typeof core_workspaces_tables;
  "docs/doc404Tracking": typeof docs_doc404Tracking;
  "features/customFields/constants": typeof features_customFields_constants;
  "features/customFields/index": typeof features_customFields_index;
  "features/customFields/mutations": typeof features_customFields_mutations;
  "features/customFields/queries": typeof features_customFields_queries;
  "features/customFields/rules": typeof features_customFields_rules;
  "features/customFields/tables": typeof features_customFields_tables;
  "features/export/blog": typeof features_export_blog;
  "features/export/index": typeof features_export_index;
  "features/flashcards/auth": typeof features_flashcards_auth;
  "features/flashcards/creation": typeof features_flashcards_creation;
  "features/flashcards/importExport": typeof features_flashcards_importExport;
  "features/flashcards/importFlashcards": typeof features_flashcards_importFlashcards;
  "features/flashcards/index": typeof features_flashcards_index;
  "features/flashcards/lifecycle": typeof features_flashcards_lifecycle;
  "features/flashcards/lookups": typeof features_flashcards_lookups;
  "features/flashcards/queries": typeof features_flashcards_queries;
  "features/flashcards/repository": typeof features_flashcards_repository;
  "features/flashcards/review": typeof features_flashcards_review;
  "features/flashcards/reviewSchedule": typeof features_flashcards_reviewSchedule;
  "features/flashcards/settings": typeof features_flashcards_settings;
  "features/flashcards/state": typeof features_flashcards_state;
  "features/flashcards/stats": typeof features_flashcards_stats;
  "features/flashcards/tables": typeof features_flashcards_tables;
  "features/flashcards/tags": typeof features_flashcards_tags;
  "features/inbox/access": typeof features_inbox_access;
  "features/inbox/assignments": typeof features_inbox_assignments;
  "features/inbox/index": typeof features_inbox_index;
  "features/inbox/lifecycle": typeof features_inbox_lifecycle;
  "features/inbox/notifications": typeof features_inbox_notifications;
  "features/inbox/queries": typeof features_inbox_queries;
  "features/inbox/tables": typeof features_inbox_tables;
  "features/invites/helpers": typeof features_invites_helpers;
  "features/invites/index": typeof features_invites_index;
  "features/invites/mutations": typeof features_invites_mutations;
  "features/invites/queries": typeof features_invites_queries;
  "features/invites/rules": typeof features_invites_rules;
  "features/invites/tables": typeof features_invites_tables;
  "features/meetings/agendaItems": typeof features_meetings_agendaItems;
  "features/meetings/helpers/access": typeof features_meetings_helpers_access;
  "features/meetings/helpers/invitations": typeof features_meetings_helpers_invitations;
  "features/meetings/helpers/invitations/index": typeof features_meetings_helpers_invitations_index;
  "features/meetings/helpers/invitations/mutations": typeof features_meetings_helpers_invitations_mutations;
  "features/meetings/helpers/invitations/queries": typeof features_meetings_helpers_invitations_queries;
  "features/meetings/helpers/meetingMutations": typeof features_meetings_helpers_meetingMutations;
  "features/meetings/helpers/meetingQueries": typeof features_meetings_helpers_meetingQueries;
  "features/meetings/helpers/mutations/agendaItems": typeof features_meetings_helpers_mutations_agendaItems;
  "features/meetings/helpers/mutations/archive": typeof features_meetings_helpers_mutations_archive;
  "features/meetings/helpers/mutations/attendees": typeof features_meetings_helpers_mutations_attendees;
  "features/meetings/helpers/mutations/createUpdate": typeof features_meetings_helpers_mutations_createUpdate;
  "features/meetings/helpers/mutations/index": typeof features_meetings_helpers_mutations_index;
  "features/meetings/helpers/mutations/lifecycle": typeof features_meetings_helpers_mutations_lifecycle;
  "features/meetings/helpers/mutations/session": typeof features_meetings_helpers_mutations_session;
  "features/meetings/helpers/queries/agendaItems": typeof features_meetings_helpers_queries_agendaItems;
  "features/meetings/helpers/queries/get": typeof features_meetings_helpers_queries_get;
  "features/meetings/helpers/queries/index": typeof features_meetings_helpers_queries_index;
  "features/meetings/helpers/queries/invitedUsers": typeof features_meetings_helpers_queries_invitedUsers;
  "features/meetings/helpers/queries/invitedUsersUtils": typeof features_meetings_helpers_queries_invitedUsersUtils;
  "features/meetings/helpers/queries/list": typeof features_meetings_helpers_queries_list;
  "features/meetings/helpers/queries/listByCircle": typeof features_meetings_helpers_queries_listByCircle;
  "features/meetings/helpers/queries/listByTemplate": typeof features_meetings_helpers_queries_listByTemplate;
  "features/meetings/helpers/queries/listForUser": typeof features_meetings_helpers_queries_listForUser;
  "features/meetings/helpers/queries/shared": typeof features_meetings_helpers_queries_shared;
  "features/meetings/helpers/templates": typeof features_meetings_helpers_templates;
  "features/meetings/helpers/templates/index": typeof features_meetings_helpers_templates_index;
  "features/meetings/helpers/templates/mutations": typeof features_meetings_helpers_templates_mutations;
  "features/meetings/helpers/templates/queries": typeof features_meetings_helpers_templates_queries;
  "features/meetings/helpers/templates/steps": typeof features_meetings_helpers_templates_steps;
  "features/meetings/index": typeof features_meetings_index;
  "features/meetings/invitations": typeof features_meetings_invitations;
  "features/meetings/meetings": typeof features_meetings_meetings;
  "features/meetings/presence": typeof features_meetings_presence;
  "features/meetings/tables": typeof features_meetings_tables;
  "features/meetings/templates": typeof features_meetings_templates;
  "features/notes/index": typeof features_notes_index;
  "features/onboarding/index": typeof features_onboarding_index;
  "features/onboarding/mutations": typeof features_onboarding_mutations;
  "features/onboarding/queries": typeof features_onboarding_queries;
  "features/onboarding/rules": typeof features_onboarding_rules;
  "features/onboarding/tables": typeof features_onboarding_tables;
  "features/projects/index": typeof features_projects_index;
  "features/projects/tables": typeof features_projects_tables;
  "features/readwise/access": typeof features_readwise_access;
  "features/readwise/api": typeof features_readwise_api;
  "features/readwise/cleanup": typeof features_readwise_cleanup;
  "features/readwise/fetch": typeof features_readwise_fetch;
  "features/readwise/filters": typeof features_readwise_filters;
  "features/readwise/highlights": typeof features_readwise_highlights;
  "features/readwise/index": typeof features_readwise_index;
  "features/readwise/jobs": typeof features_readwise_jobs;
  "features/readwise/mutations": typeof features_readwise_mutations;
  "features/readwise/mutations/authorsSources": typeof features_readwise_mutations_authorsSources;
  "features/readwise/mutations/highlights": typeof features_readwise_mutations_highlights;
  "features/readwise/mutations/index": typeof features_readwise_mutations_index;
  "features/readwise/mutations/progress": typeof features_readwise_mutations_progress;
  "features/readwise/mutations/queries": typeof features_readwise_mutations_queries;
  "features/readwise/mutations/tags": typeof features_readwise_mutations_tags;
  "features/readwise/orchestrator": typeof features_readwise_orchestrator;
  "features/readwise/persistence": typeof features_readwise_persistence;
  "features/readwise/progress": typeof features_readwise_progress;
  "features/readwise/queries/progress": typeof features_readwise_queries_progress;
  "features/readwise/sources": typeof features_readwise_sources;
  "features/readwise/sync": typeof features_readwise_sync;
  "features/readwise/tables": typeof features_readwise_tables;
  "features/readwise/testApi": typeof features_readwise_testApi;
  "features/readwise/transform": typeof features_readwise_transform;
  "features/readwise/utils": typeof features_readwise_utils;
  "features/tags/access": typeof features_tags_access;
  "features/tags/assignments": typeof features_tags_assignments;
  "features/tags/hierarchy": typeof features_tags_hierarchy;
  "features/tags/index": typeof features_tags_index;
  "features/tags/lifecycle": typeof features_tags_lifecycle;
  "features/tags/queries": typeof features_tags_queries;
  "features/tags/tables": typeof features_tags_tables;
  "features/tags/types": typeof features_tags_types;
  "features/tags/validation": typeof features_tags_validation;
  "features/tasks/access": typeof features_tasks_access;
  "features/tasks/assignments": typeof features_tasks_assignments;
  "features/tasks/index": typeof features_tasks_index;
  "features/tasks/lifecycle": typeof features_tasks_lifecycle;
  "features/tasks/mutations": typeof features_tasks_mutations;
  "features/tasks/queries": typeof features_tasks_queries;
  "features/tasks/tables": typeof features_tasks_tables;
  "features/tasks/types": typeof features_tasks_types;
  "features/waitlist/index": typeof features_waitlist_index;
  "features/workspaceBranding/index": typeof features_workspaceBranding_index;
  "features/workspaceSettings/index": typeof features_workspaceSettings_index;
  "features/workspaces/index": typeof features_workspaces_index;
  "features/workspaces/members": typeof features_workspaces_members;
  http: typeof http;
  "infrastructure/access/permissions": typeof infrastructure_access_permissions;
  "infrastructure/access/withCircleAccess": typeof infrastructure_access_withCircleAccess;
  "infrastructure/access/workspaceRoles": typeof infrastructure_access_workspaceRoles;
  "infrastructure/auth": typeof infrastructure_auth;
  "infrastructure/auth/helpers": typeof infrastructure_auth_helpers;
  "infrastructure/auth/tables": typeof infrastructure_auth_tables;
  "infrastructure/auth/validateApiKeys": typeof infrastructure_auth_validateApiKeys;
  "infrastructure/auth/verification": typeof infrastructure_auth_verification;
  "infrastructure/authSessions": typeof infrastructure_authSessions;
  "infrastructure/crypto": typeof infrastructure_crypto;
  "infrastructure/customFields/helpers": typeof infrastructure_customFields_helpers;
  "infrastructure/customFields/index": typeof infrastructure_customFields_index;
  "infrastructure/db/withActiveFilter": typeof infrastructure_db_withActiveFilter;
  "infrastructure/email": typeof infrastructure_email;
  "infrastructure/errors/codes": typeof infrastructure_errors_codes;
  "infrastructure/featureFlags": typeof infrastructure_featureFlags;
  "infrastructure/featureFlags/access": typeof infrastructure_featureFlags_access;
  "infrastructure/featureFlags/debug": typeof infrastructure_featureFlags_debug;
  "infrastructure/featureFlags/impact": typeof infrastructure_featureFlags_impact;
  "infrastructure/featureFlags/lifecycle": typeof infrastructure_featureFlags_lifecycle;
  "infrastructure/featureFlags/queries": typeof infrastructure_featureFlags_queries;
  "infrastructure/featureFlags/store": typeof infrastructure_featureFlags_store;
  "infrastructure/featureFlags/targeting": typeof infrastructure_featureFlags_targeting;
  "infrastructure/featureFlags/types": typeof infrastructure_featureFlags_types;
  "infrastructure/featureFlags/utils": typeof infrastructure_featureFlags_utils;
  "infrastructure/featureFlags/validation": typeof infrastructure_featureFlags_validation;
  "infrastructure/http": typeof infrastructure_http;
  "infrastructure/posthog": typeof infrastructure_posthog;
  "infrastructure/rbac/permissions": typeof infrastructure_rbac_permissions;
  "infrastructure/rbac/permissions/access": typeof infrastructure_rbac_permissions_access;
  "infrastructure/rbac/permissions/lifecycle": typeof infrastructure_rbac_permissions_lifecycle;
  "infrastructure/rbac/permissions/logging": typeof infrastructure_rbac_permissions_logging;
  "infrastructure/rbac/permissions/queries": typeof infrastructure_rbac_permissions_queries;
  "infrastructure/rbac/permissions/types": typeof infrastructure_rbac_permissions_types;
  "infrastructure/rbac/permissions/validation": typeof infrastructure_rbac_permissions_validation;
  "infrastructure/rbac/queries": typeof infrastructure_rbac_queries;
  "infrastructure/rbac/roles": typeof infrastructure_rbac_roles;
  "infrastructure/rbac/scopeHelpers": typeof infrastructure_rbac_scopeHelpers;
  "infrastructure/rbac/seedRBAC": typeof infrastructure_rbac_seedRBAC;
  "infrastructure/rbac/setupAdmin": typeof infrastructure_rbac_setupAdmin;
  "infrastructure/rbac/tables": typeof infrastructure_rbac_tables;
  "infrastructure/sessionValidation": typeof infrastructure_sessionValidation;
  "infrastructure/tables": typeof infrastructure_tables;
  "infrastructure/types/prosemirror": typeof infrastructure_types_prosemirror;
  "infrastructure/urls": typeof infrastructure_urls;
  "migrations/clearPeopleEmailDenormalization": typeof migrations_clearPeopleEmailDenormalization;
  "prompts/flashcardGeneration": typeof prompts_flashcardGeneration;
  "prompts/utils": typeof prompts_utils;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
