/**
 * Mock Data for "My Brain" Input Sources
 * 
 * This file contains mock data with 5 items per input source type.
 * Only INPUT sources are included (raw data users put INTO the system).
 * 
 * Outputs (flashcards, processed notes) are excluded.
 */

export type InputSourceType =
  // Reading & Literature
  | 'readwise_highlight'
  | 'readwise_reader_document'
  | 'manual_text'
  | 'web_article'
  | 'url_bookmark'
  | 'photo_note'
  | 'screenshot'
  | 'email'
  | 'voice_memo'
  | 'code_snippet'
  | 'meeting_note'
  | 'newsletter'
  | 'social_media_post'
  | 'podcast_transcript'
  | 'video_transcript'
  | 'pdf_document'
  | 'word_document'
  | 'annotation'
  | 'slack_message'
  | 'calendar_event_note'
  | 'checklist';

export interface MockInboxItem {
  _id: string;
  type: InputSourceType;
  userId: string;
  processed: boolean;
  processedAt?: number;
  createdAt: number;
  // Display fields (enriched)
  title: string;
  snippet: string;
  tags: string[];
  // Type-specific data
  [key: string]: any;
}

const now = Date.now();
const oneDay = 24 * 60 * 60 * 1000;

export const mockBrainInputs: MockInboxItem[] = [
  // ==========================================
  // 📚 Reading & Literature
  // ==========================================

  // readwise_highlight
  {
    _id: 'rw1',
    type: 'readwise_highlight',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'The Lean Startup - Build-Measure-Learn',
    snippet: 'The fundamental activity of a startup is to turn ideas into products, measure how customers respond, and then learn whether to pivot or persevere.',
    tags: ['product', 'startup', 'methodology'],
    highlightId: 'hl1',
    sourceTitle: 'The Lean Startup',
    author: 'Eric Ries',
    location: 45,
    locationType: 'page',
  },
  {
    _id: 'rw2',
    type: 'readwise_highlight',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Continuous Discovery Habits - Customer Interviews',
    snippet: 'Talk to at least one customer every week, even when it feels uncomfortable or you think you already know the answer.',
    tags: ['product', 'discovery', 'customer-research'],
    highlightId: 'hl2',
    sourceTitle: 'Continuous Discovery Habits',
    author: 'Teresa Torres',
    location: 120,
    locationType: 'page',
  },
  {
    _id: 'rw3',
    type: 'readwise_highlight',
    userId: 'user1',
    processed: true,
    processedAt: now - 2 * oneDay,
    createdAt: now - 3 * oneDay,
    title: 'Hooked - User Behavior',
    snippet: 'Understanding the "why" behind user behavior is more valuable than tracking the "what". Focus on motivation and triggers.',
    tags: ['product', 'psychology', 'user-behavior'],
    highlightId: 'hl3',
    sourceTitle: 'Hooked',
    author: 'Nir Eyal',
    location: 89,
    locationType: 'page',
  },
  {
    _id: 'rw4',
    type: 'readwise_highlight',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Inspired - Product Manager Role',
    snippet: 'The best product managers are product champions who combine deep user empathy, clear product vision, and relentless execution.',
    tags: ['product', 'leadership', 'pm'],
    highlightId: 'hl4',
    sourceTitle: 'Inspired',
    author: 'Marty Cagan',
    location: 156,
    locationType: 'page',
  },
  {
    _id: 'rw5',
    type: 'readwise_highlight',
    userId: 'user1',
    processed: false,
    createdAt: now - 6 * 60 * 60 * 1000, // 6 hours ago
    title: 'Shape Up - Dual-Track Agile',
    snippet: 'In dual-track agile, the discovery track runs parallel to the delivery track. Discovery focuses on understanding user needs before building.',
    tags: ['product', 'agile', 'process'],
    highlightId: 'hl5',
    sourceTitle: 'Shape Up',
    author: 'Ryan Singer',
    location: 67,
    locationType: 'page',
  },

  // readwise_reader_document
  {
    _id: 'rd1',
    type: 'readwise_reader_document',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'The Future of AI in Product Management',
    snippet: 'A comprehensive look at how AI tools are transforming the product management landscape, from user research to feature prioritization...',
    tags: ['ai', 'product', 'technology'],
    documentId: 'doc1',
    url: 'https://example.com/ai-product-management',
    author: 'Sarah Chen',
    category: 'article',
  },
  {
    _id: 'rd2',
    type: 'readwise_reader_document',
    userId: 'user1',
    processed: false,
    createdAt: now - 3 * oneDay,
    title: 'Building Effective Product Teams',
    snippet: 'What makes a product team successful? This article explores the key ingredients: trust, autonomy, clear goals, and shared vision...',
    tags: ['team', 'leadership', 'product'],
    documentId: 'doc2',
    url: 'https://example.com/product-teams',
    author: 'Michael Johnson',
    category: 'article',
  },
  {
    _id: 'rd3',
    type: 'readwise_reader_document',
    userId: 'user1',
    processed: true,
    processedAt: now - 1 * oneDay,
    createdAt: now - 5 * oneDay,
    title: 'User Research Methods: A Practical Guide',
    snippet: 'An in-depth guide to user research methods, from interviews and surveys to usability testing and ethnographic studies...',
    tags: ['research', 'ux', 'user-research'],
    documentId: 'doc3',
    url: 'https://example.com/user-research',
    author: 'Emma Davis',
    category: 'article',
  },
  {
    _id: 'rd4',
    type: 'readwise_reader_document',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'The Psychology of Pricing',
    snippet: 'How pricing psychology influences consumer behavior and decision-making. Understanding anchors, decoys, and perceived value...',
    tags: ['business', 'psychology', 'pricing'],
    documentId: 'doc4',
    url: 'https://example.com/pricing-psychology',
    author: 'David Lee',
    category: 'article',
  },
  {
    _id: 'rd5',
    type: 'readwise_reader_document',
    userId: 'user1',
    processed: false,
    createdAt: now - 6 * oneDay,
    title: 'Agile vs Waterfall: When to Use Each',
    snippet: 'A comparison of agile and waterfall methodologies, exploring when each approach is most appropriate for different types of projects...',
    tags: ['agile', 'methodology', 'project-management'],
    documentId: 'doc5',
    url: 'https://example.com/agile-waterfall',
    author: 'Lisa Wang',
    category: 'article',
  },

  // ==========================================
  // 📝 Text & Notes
  // ==========================================

  // manual_text
  {
    _id: 'mt1',
    type: 'manual_text',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Product Vision Ideas',
    snippet: 'What if we could create a product that helps teams make better decisions faster? Focus on reducing decision fatigue...',
    tags: ['ideas', 'product-vision'],
    text: 'What if we could create a product that helps teams make better decisions faster? Focus on reducing decision fatigue and providing clear data-driven insights.',
    bookTitle: undefined,
    pageNumber: undefined,
  },
  {
    _id: 'mt2',
    type: 'manual_text',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'Meeting Reflection',
    snippet: 'Today\'s sprint planning went well. Key insight: We need to focus more on user feedback loops...',
    tags: ['reflection', 'meeting'],
    text: "Today's sprint planning went well. Key insight: We need to focus more on user feedback loops. The team is excited about the new feature direction.",
    bookTitle: undefined,
    pageNumber: undefined,
  },
  {
    _id: 'mt3',
    type: 'manual_text',
    userId: 'user1',
    processed: true,
    processedAt: now - 12 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Learning Notes: Design Systems',
    snippet: 'Design systems are more than just component libraries. They\'re a shared language for teams...',
    tags: ['learning', 'design', 'systems'],
    text: 'Design systems are more than just component libraries. They\'re a shared language for teams, enabling consistency and speed.',
    bookTitle: undefined,
    pageNumber: undefined,
  },
  {
    _id: 'mt4',
    type: 'manual_text',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Quick Thought: Feature Prioritization',
    snippet: 'When prioritizing features, ask: Does this solve a real user problem? Can we validate it quickly?',
    tags: ['prioritization', 'product'],
    text: 'When prioritizing features, ask: Does this solve a real user problem? Can we validate it quickly? What\'s the impact vs effort?',
    bookTitle: undefined,
    pageNumber: undefined,
  },
  {
    _id: 'mt5',
    type: 'manual_text',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'Book Quote: Thinking Fast and Slow',
    snippet: 'System 1 is fast, intuitive, and emotional. System 2 is slow, deliberate, and logical...',
    tags: ['psychology', 'thinking'],
    text: 'System 1 is fast, intuitive, and emotional. System 2 is slow, deliberate, and logical. Most of our decisions are made by System 1.',
    bookTitle: 'Thinking Fast and Slow',
    pageNumber: 23,
  },

  // ==========================================
  // 🌐 Web & Online Content
  // ==========================================

  // web_article
  {
    _id: 'wa1',
    type: 'web_article',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: '10 Product Management Frameworks You Should Know',
    snippet: 'From RICE to ICE to Kano Model, here are the essential frameworks every product manager needs in their toolkit...',
    tags: ['product', 'frameworks', 'tools'],
    url: 'https://example.com/pm-frameworks',
    author: 'ProductHunt',
    publishedAt: now - 7 * oneDay,
  },
  {
    _id: 'wa2',
    type: 'web_article',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'The Art of User Story Writing',
    snippet: 'Writing effective user stories is both an art and a science. Learn how to craft stories that drive action...',
    tags: ['agile', 'user-stories', 'writing'],
    url: 'https://example.com/user-stories',
    author: 'Agile Alliance',
    publishedAt: now - 14 * oneDay,
  },
  {
    _id: 'wa3',
    type: 'web_article',
    userId: 'user1',
    processed: true,
    processedAt: now - 18 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Building a Product Strategy from Scratch',
    snippet: 'How to develop a comprehensive product strategy that aligns with business goals and user needs...',
    tags: ['strategy', 'product', 'planning'],
    url: 'https://example.com/product-strategy',
    author: 'Mind the Product',
    publishedAt: now - 21 * oneDay,
  },
  {
    _id: 'wa4',
    type: 'web_article',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'A/B Testing Best Practices',
    snippet: 'Learn how to design and run effective A/B tests that yield actionable insights for product decisions...',
    tags: ['testing', 'data', 'experimentation'],
    url: 'https://example.com/ab-testing',
    author: 'ConversionXL',
    publishedAt: now - 10 * oneDay,
  },
  {
    _id: 'wa5',
    type: 'web_article',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'The Future of Remote Product Teams',
    snippet: 'How remote-first product teams are redefining collaboration and productivity in the post-pandemic world...',
    tags: ['remote', 'team', 'collaboration'],
    url: 'https://example.com/remote-teams',
    author: 'Remote.co',
    publishedAt: now - 30 * oneDay,
  },

  // url_bookmark
  {
    _id: 'ub1',
    type: 'url_bookmark',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Product Metrics Dashboard Template',
    snippet: 'A comprehensive dashboard template for tracking key product metrics and KPIs...',
    tags: ['metrics', 'dashboard', 'analytics'],
    url: 'https://example.com/metrics-dashboard',
    description: 'Free template for product metrics tracking',
  },
  {
    _id: 'ub2',
    type: 'url_bookmark',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'User Interview Question Bank',
    snippet: 'A curated collection of user interview questions organized by topic and use case...',
    tags: ['research', 'interviews', 'questions'],
    url: 'https://example.com/interview-questions',
    description: 'Essential questions for user research',
  },
  {
    _id: 'ub3',
    type: 'url_bookmark',
    userId: 'user1',
    processed: true,
    processedAt: now - 3 * oneDay,
    createdAt: now - 3 * oneDay,
    title: 'Design System Documentation',
    snippet: 'Complete guide to building and maintaining a design system for product teams...',
    tags: ['design', 'systems', 'documentation'],
    url: 'https://example.com/design-system',
    description: 'Design system best practices',
  },
  {
    _id: 'ub4',
    type: 'url_bookmark',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'API Documentation Tool',
    snippet: 'Tool for creating beautiful, interactive API documentation...',
    tags: ['api', 'documentation', 'tools'],
    url: 'https://example.com/api-docs',
    description: 'API docs generator',
  },
  {
    _id: 'ub5',
    type: 'url_bookmark',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'Product Roadmap Template',
    snippet: 'Free template for creating product roadmaps with multiple view options...',
    tags: ['roadmap', 'planning', 'template'],
    url: 'https://example.com/roadmap-template',
    description: 'Product roadmap template',
  },

  // ==========================================
  // 🖼️ Visual Content
  // ==========================================

  // photo_note
  {
    _id: 'pn1',
    type: 'photo_note',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Whiteboard: User Journey Map',
    snippet: 'Photo of whiteboard session mapping out the user journey for our new feature...',
    tags: ['whiteboard', 'user-journey', 'planning'],
    imageFileId: 'img1',
    transcribedText: 'User Journey Map: Discovery → Consideration → Purchase → Onboarding → Engagement',
    source: 'iPhone Camera',
    ocrStatus: 'completed',
  },
  {
    _id: 'pn2',
    type: 'photo_note',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'Book Page: Product Strategy',
    snippet: 'Photo of key page from "Inspired" book about product strategy...',
    tags: ['book', 'strategy', 'photo'],
    imageFileId: 'img2',
    transcribedText: 'The best product strategies are those that clearly articulate the problem space, target users, and success metrics.',
    source: 'iPhone Camera',
    ocrStatus: 'completed',
  },
  {
    _id: 'pn3',
    type: 'photo_note',
    userId: 'user1',
    processed: true,
    processedAt: now - 12 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Handwritten Notes: Sprint Planning',
    snippet: 'Handwritten notes from sprint planning meeting with key decisions...',
    tags: ['handwritten', 'meeting', 'sprint'],
    imageFileId: 'img3',
    transcribedText: 'Sprint Planning: Focus on user authentication improvements. Prioritize security features.',
    source: 'iPad Camera',
    ocrStatus: 'completed',
  },
  {
    _id: 'pn4',
    type: 'photo_note',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Diagram: System Architecture',
    snippet: 'Photo of system architecture diagram drawn during team discussion...',
    tags: ['architecture', 'diagram', 'technical'],
    imageFileId: 'img4',
    transcribedText: 'System Architecture: Frontend → API Gateway → Microservices → Database',
    source: 'iPhone Camera',
    ocrStatus: 'completed',
  },
  {
    _id: 'pn5',
    type: 'photo_note',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'Conference Slide: Product Metrics',
    snippet: 'Photo of slide from product conference about key metrics...',
    tags: ['conference', 'metrics', 'slide'],
    imageFileId: 'img5',
    transcribedText: 'Key Product Metrics: DAU, Retention Rate, Revenue per User, Feature Adoption',
    source: 'iPhone Camera',
    ocrStatus: 'completed',
  },

  // screenshot
  {
    _id: 'ss1',
    type: 'screenshot',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Analytics Dashboard Screenshot',
    snippet: 'Screenshot of user analytics dashboard showing key metrics...',
    tags: ['analytics', 'dashboard', 'screenshot'],
    imageFileId: 'img6',
    source: 'macOS Screenshot',
    device: 'MacBook Pro',
  },
  {
    _id: 'ss2',
    type: 'screenshot',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'Competitor Feature Analysis',
    snippet: 'Screenshot comparing competitor product features...',
    tags: ['competitor', 'analysis', 'screenshot'],
    imageFileId: 'img7',
    source: 'Chrome Screenshot',
    device: 'MacBook Pro',
  },
  {
    _id: 'ss3',
    type: 'screenshot',
    userId: 'user1',
    processed: true,
    processedAt: now - 18 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'User Feedback Email',
    snippet: 'Screenshot of important user feedback email...',
    tags: ['feedback', 'user', 'screenshot'],
    imageFileId: 'img8',
    source: 'macOS Screenshot',
    device: 'MacBook Pro',
  },
  {
    _id: 'ss4',
    type: 'screenshot',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Error Message Screenshot',
    snippet: 'Screenshot of error message for debugging purposes...',
    tags: ['bug', 'error', 'screenshot'],
    imageFileId: 'img9',
    source: 'iOS Screenshot',
    device: 'iPhone',
  },
  {
    _id: 'ss5',
    type: 'screenshot',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'Design Mockup Screenshot',
    snippet: 'Screenshot of design mockup for new feature...',
    tags: ['design', 'mockup', 'screenshot'],
    imageFileId: 'img10',
    source: 'Figma Screenshot',
    device: 'MacBook Pro',
  },

  // ==========================================
  // 📧 Communication
  // ==========================================

  // email
  {
    _id: 'em1',
    type: 'email',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'User Feedback: Feature Request',
    snippet: 'User feedback email requesting new feature for better collaboration...',
    tags: ['feedback', 'feature-request', 'user'],
    emailId: 'email1',
    subject: 'Feature Request: Collaborative Editing',
    sender: 'user@example.com',
    senderName: 'Sarah Johnson',
    receivedAt: now - 1 * oneDay,
  },
  {
    _id: 'em2',
    type: 'email',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'Product Update: Q4 Roadmap',
    snippet: 'Email from product lead sharing Q4 roadmap and priorities...',
    tags: ['roadmap', 'product', 'update'],
    emailId: 'email2',
    subject: 'Q4 Product Roadmap Update',
    sender: 'product-lead@company.com',
    senderName: 'Mike Chen',
    receivedAt: now - 2 * oneDay,
  },
  {
    _id: 'em3',
    type: 'email',
    userId: 'user1',
    processed: true,
    processedAt: now - 12 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Customer Success Story',
    snippet: 'Success story email from customer about how our product helped them...',
    tags: ['customer', 'success', 'story'],
    emailId: 'email3',
    subject: 'Customer Success Story: Acme Corp',
    sender: 'cs@company.com',
    senderName: 'Customer Success Team',
    receivedAt: now - 3 * oneDay,
  },
  {
    _id: 'em4',
    type: 'email',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Research Study Invitation',
    snippet: 'Email invitation to participate in user research study...',
    tags: ['research', 'invitation', 'study'],
    emailId: 'email4',
    subject: 'Invitation: User Research Study',
    sender: 'research@company.com',
    senderName: 'Research Team',
    receivedAt: now - 4 * oneDay,
  },
  {
    _id: 'em5',
    type: 'email',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'Technical Documentation Link',
    snippet: 'Email with link to important technical documentation...',
    tags: ['documentation', 'technical', 'link'],
    emailId: 'email5',
    subject: 'New API Documentation Available',
    sender: 'dev-team@company.com',
    senderName: 'Development Team',
    receivedAt: now - 5 * oneDay,
  },

  // ==========================================
  // 🎤 Audio & Voice
  // ==========================================

  // voice_memo
  {
    _id: 'vm1',
    type: 'voice_memo',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Voice Memo: Product Idea',
    snippet: 'Quick voice memo about a new product idea for mobile app features...',
    tags: ['ideas', 'voice', 'product'],
    audioFileId: 'audio1',
    transcribedText: 'I had an idea for a new mobile feature that could help users collaborate better. We should explore this in the next sprint.',
    duration: 45, // seconds
    source: 'iPhone Voice Memos',
  },
  {
    _id: 'vm2',
    type: 'voice_memo',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'Voice Memo: Meeting Notes',
    snippet: 'Voice memo summarizing key points from team meeting...',
    tags: ['meeting', 'notes', 'voice'],
    audioFileId: 'audio2',
    transcribedText: 'Key points from today\'s meeting: Focus on user authentication, prioritize security features, and schedule follow-up.',
    duration: 120,
    source: 'iPhone Voice Memos',
  },
  {
    _id: 'vm3',
    type: 'voice_memo',
    userId: 'user1',
    processed: true,
    processedAt: now - 18 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Voice Memo: User Feedback',
    snippet: 'Voice memo recording user feedback from phone call...',
    tags: ['feedback', 'user', 'voice'],
    audioFileId: 'audio3',
    transcribedText: 'User feedback: They love the new feature but want better mobile experience. Consider mobile-first improvements.',
    duration: 90,
    source: 'iPhone Voice Memos',
  },
  {
    _id: 'vm4',
    type: 'voice_memo',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Voice Memo: Reflection',
    snippet: 'Voice memo reflecting on product launch and lessons learned...',
    tags: ['reflection', 'launch', 'voice'],
    audioFileId: 'audio4',
    transcribedText: 'Reflection on the product launch: We did well on user engagement but need to improve onboarding flow.',
    duration: 180,
    source: 'iPhone Voice Memos',
  },
  {
    _id: 'vm5',
    type: 'voice_memo',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'Voice Memo: Quick Thought',
    snippet: 'Quick voice memo about potential feature improvement...',
    tags: ['ideas', 'quick-thought', 'voice'],
    audioFileId: 'audio5',
    transcribedText: 'Quick thought: What if we add a notification system for important updates? Could improve user engagement.',
    duration: 30,
    source: 'iPhone Voice Memos',
  },

  // ==========================================
  // 💻 Code & Technical
  // ==========================================

  // code_snippet
  {
    _id: 'cs1',
    type: 'code_snippet',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'API Authentication Code',
    snippet: 'Code snippet for implementing JWT authentication in API...',
    tags: ['code', 'api', 'authentication'],
    code: "const authenticate = async (token: string) => {\n  const decoded = jwt.verify(token, process.env.JWT_SECRET);\n  return decoded;\n};",
    language: 'typescript',
    description: 'JWT authentication helper function',
  },
  {
    _id: 'cs2',
    type: 'code_snippet',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'React Hook: useDebounce',
    snippet: 'Custom React hook for debouncing input values...',
    tags: ['code', 'react', 'hooks'],
    code: "const useDebounce = (value: string, delay: number) => {\n  const [debouncedValue, setDebouncedValue] = useState(value);\n  useEffect(() => {\n    const handler = setTimeout(() => setDebouncedValue(value), delay);\n    return () => clearTimeout(handler);\n  }, [value, delay]);\n  return debouncedValue;\n};",
    language: 'typescript',
    description: 'Debounce hook for React',
  },
  {
    _id: 'cs3',
    type: 'code_snippet',
    userId: 'user1',
    processed: true,
    processedAt: now - 12 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Database Query: User Stats',
    snippet: 'SQL query for calculating user engagement statistics...',
    tags: ['code', 'sql', 'database'],
    code: "SELECT \n  user_id,\n  COUNT(*) as total_actions,\n  DATE(created_at) as date\nFROM user_actions\nWHERE created_at >= NOW() - INTERVAL '30 days'\nGROUP BY user_id, DATE(created_at);",
    language: 'sql',
    description: 'User engagement stats query',
  },
  {
    _id: 'cs4',
    type: 'code_snippet',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Error Handling Pattern',
    snippet: 'Error handling pattern for async operations...',
    tags: ['code', 'error-handling', 'patterns'],
    code: "try {\n  const result = await asyncOperation();\n  return { success: true, data: result };\n} catch (error) {\n  console.error('Operation failed:', error);\n  return { success: false, error: error.message };\n}",
    language: 'typescript',
    description: 'Error handling wrapper',
  },
  {
    _id: 'cs5',
    type: 'code_snippet',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'Utility Function: Format Date',
    snippet: 'Utility function for formatting dates in consistent format...',
    tags: ['code', 'utilities', 'date'],
    code: "const formatDate = (date: Date): string => {\n  return new Intl.DateTimeFormat('en-US', {\n    year: 'numeric',\n    month: 'long',\n    day: 'numeric'\n  }).format(date);\n};",
    language: 'typescript',
    description: 'Date formatting utility',
  },

  // ==========================================
  // 📋 Meetings & Notes
  // ==========================================

  // meeting_note
  {
    _id: 'mn1',
    type: 'meeting_note',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Sprint Planning Meeting Notes',
    snippet: 'Notes from sprint planning meeting covering feature prioritization and team assignments...',
    tags: ['meeting', 'sprint', 'planning'],
    meetingDate: now - 1 * oneDay,
    attendees: ['John Doe', 'Jane Smith', 'Mike Chen'],
    keyPoints: [
      'Prioritize user authentication improvements',
      'Focus on mobile experience enhancements',
      'Schedule user research sessions',
    ],
  },
  {
    _id: 'mn2',
    type: 'meeting_note',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'User Research Debrief',
    snippet: 'Debrief notes from user research session with key insights and action items...',
    tags: ['meeting', 'research', 'user'],
    meetingDate: now - 2 * oneDay,
    attendees: ['Sarah Johnson', 'Research Team'],
    keyPoints: [
      'Users want better mobile experience',
      'Key pain point: onboarding complexity',
      'Action: Simplify onboarding flow',
    ],
  },
  {
    _id: 'mn3',
    type: 'meeting_note',
    userId: 'user1',
    processed: true,
    processedAt: now - 18 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Product Review Meeting',
    snippet: 'Product review meeting notes covering Q4 performance and Q1 planning...',
    tags: ['meeting', 'review', 'product'],
    meetingDate: now - 3 * oneDay,
    attendees: ['Product Team', 'Leadership'],
    keyPoints: [
      'Q4 goals achieved',
      'Q1 focus: user engagement',
      'New feature roadmap approved',
    ],
  },
  {
    _id: 'mn4',
    type: 'meeting_note',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Design Critique Session',
    snippet: 'Design critique session notes with feedback on new feature mockups...',
    tags: ['meeting', 'design', 'feedback'],
    meetingDate: now - 4 * oneDay,
    attendees: ['Design Team', 'Product Team'],
    keyPoints: [
      'Improve mobile navigation',
      'Enhance visual hierarchy',
      'Consider accessibility improvements',
    ],
  },
  {
    _id: 'mn5',
    type: 'meeting_note',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'Retrospective Notes',
    snippet: 'Sprint retrospective notes covering what went well and what to improve...',
    tags: ['meeting', 'retrospective', 'sprint'],
    meetingDate: now - 5 * oneDay,
    attendees: ['Development Team'],
    keyPoints: [
      'Good: Communication improved',
      'Improve: Code review process',
      'Action: Set up automated testing',
    ],
  },

  // ==========================================
  // 📰 Newsletters & Subscriptions
  // ==========================================

  // newsletter
  {
    _id: 'nl1',
    type: 'newsletter',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'ProductHunt Weekly: Top Products',
    snippet: 'Weekly newsletter featuring top product launches and startup news...',
    tags: ['newsletter', 'products', 'startups'],
    newsletterName: 'ProductHunt Weekly',
    sender: 'newsletter@producthunt.com',
    publishedAt: now - 1 * oneDay,
  },
  {
    _id: 'nl2',
    type: 'newsletter',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'Mind the Product: Product Management Insights',
    snippet: 'Monthly newsletter with product management insights and case studies...',
    tags: ['newsletter', 'product', 'management'],
    newsletterName: 'Mind the Product',
    sender: 'newsletter@mindtheproduct.com',
    publishedAt: now - 2 * oneDay,
  },
  {
    _id: 'nl3',
    type: 'newsletter',
    userId: 'user1',
    processed: true,
    processedAt: now - 12 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'UX Design Weekly: Design Trends',
    snippet: 'Weekly newsletter covering UX design trends and best practices...',
    tags: ['newsletter', 'ux', 'design'],
    newsletterName: 'UX Design Weekly',
    sender: 'newsletter@uxdesignweekly.com',
    publishedAt: now - 3 * oneDay,
  },
  {
    _id: 'nl4',
    type: 'newsletter',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'TechCrunch: Startup News',
    snippet: 'Daily newsletter with latest startup news and funding announcements...',
    tags: ['newsletter', 'tech', 'startups'],
    newsletterName: 'TechCrunch',
    sender: 'newsletter@techcrunch.com',
    publishedAt: now - 4 * oneDay,
  },
  {
    _id: 'nl5',
    type: 'newsletter',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'First Round Review: Startup Advice',
    snippet: 'Monthly newsletter with startup advice and founder stories...',
    tags: ['newsletter', 'startups', 'advice'],
    newsletterName: 'First Round Review',
    sender: 'newsletter@firstround.com',
    publishedAt: now - 5 * oneDay,
  },

  // ==========================================
  // 📱 Social Media
  // ==========================================

  // social_media_post
  {
    _id: 'sm1',
    type: 'social_media_post',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Twitter: Product Management Tip',
    snippet: 'Great tip about user research from @ProductGuru on Twitter...',
    tags: ['twitter', 'product', 'tip'],
    platform: 'twitter',
    author: '@ProductGuru',
    postUrl: 'https://twitter.com/productguru/status/123456',
    content: 'Always start user interviews with "Tell me about..." instead of "Do you..." questions. More open-ended = better insights.',
    publishedAt: now - 1 * oneDay,
  },
  {
    _id: 'sm2',
    type: 'social_media_post',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'LinkedIn: Product Strategy Article',
    snippet: 'LinkedIn article about building effective product strategies...',
    tags: ['linkedin', 'strategy', 'product'],
    platform: 'linkedin',
    author: 'Sarah Chen',
    postUrl: 'https://linkedin.com/posts/sarahchen_product-strategy',
    content: 'The best product strategies balance user needs, business goals, and technical feasibility.',
    publishedAt: now - 2 * oneDay,
  },
  {
    _id: 'sm3',
    type: 'social_media_post',
    userId: 'user1',
    processed: true,
    processedAt: now - 18 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Reddit: Product Manager Discussion',
    snippet: 'Interesting discussion on r/ProductManagement about feature prioritization...',
    tags: ['reddit', 'discussion', 'prioritization'],
    platform: 'reddit',
    author: 'u/pm_enthusiast',
    postUrl: 'https://reddit.com/r/ProductManagement/comments/123456',
    content: 'How do you prioritize features when everything seems important? Share your frameworks!',
    publishedAt: now - 3 * oneDay,
  },
  {
    _id: 'sm4',
    type: 'social_media_post',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Twitter: Design System Insights',
    snippet: 'Twitter thread about building design systems from scratch...',
    tags: ['twitter', 'design', 'systems'],
    platform: 'twitter',
    author: '@DesignSystems',
    postUrl: 'https://twitter.com/designsystems/status/789012',
    content: 'Thread: Building a design system? Start with your design tokens, then build components, then document everything.',
    publishedAt: now - 4 * oneDay,
  },
  {
    _id: 'sm5',
    type: 'social_media_post',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'LinkedIn: User Research Best Practices',
    snippet: 'LinkedIn post sharing best practices for conducting user research...',
    tags: ['linkedin', 'research', 'user'],
    platform: 'linkedin',
    author: 'Mike Johnson',
    postUrl: 'https://linkedin.com/posts/mikejohnson_user-research',
    content: '5 tips for better user research: 1) Ask open questions 2) Listen more than talk 3) Take notes 4) Follow up 5) Synthesize insights',
    publishedAt: now - 5 * oneDay,
  },

  // ==========================================
  // 🎙️ Podcasts & Audio
  // ==========================================

  // podcast_transcript
  {
    _id: 'pt1',
    type: 'podcast_transcript',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Product Thinking Podcast: Building Great Products',
    snippet: 'Transcript from podcast episode about building great products with Marty Cagan...',
    tags: ['podcast', 'product', 'interview'],
    podcastName: 'Product Thinking',
    episodeTitle: 'Building Great Products with Marty Cagan',
    episodeNumber: 42,
    transcript: 'In this episode, we discuss what makes great products and how product managers can build better experiences...',
    duration: 3600, // seconds
    publishedAt: now - 7 * oneDay,
  },
  {
    _id: 'pt2',
    type: 'podcast_transcript',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'The Product Podcast: User Research',
    snippet: 'Transcript from podcast episode about conducting effective user research...',
    tags: ['podcast', 'research', 'user'],
    podcastName: 'The Product Podcast',
    episodeTitle: 'Mastering User Research',
    episodeNumber: 18,
    transcript: 'Learn how to conduct user research that actually drives product decisions...',
    duration: 2700,
    publishedAt: now - 14 * oneDay,
  },
  {
    _id: 'pt3',
    type: 'podcast_transcript',
    userId: 'user1',
    processed: true,
    processedAt: now - 12 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Startup Stories: Product-Market Fit',
    snippet: 'Transcript from podcast episode discussing how to find product-market fit...',
    tags: ['podcast', 'startup', 'product-market-fit'],
    podcastName: 'Startup Stories',
    episodeTitle: 'Finding Product-Market Fit',
    episodeNumber: 25,
    transcript: 'How we found product-market fit and what we learned along the way...',
    duration: 3300,
    publishedAt: now - 21 * oneDay,
  },
  {
    _id: 'pt4',
    type: 'podcast_transcript',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Design Details: Design Systems',
    snippet: 'Transcript from podcast episode about building and maintaining design systems...',
    tags: ['podcast', 'design', 'systems'],
    podcastName: 'Design Details',
    episodeTitle: 'Design Systems Done Right',
    episodeNumber: 89,
    transcript: 'Everything you need to know about building design systems that scale...',
    duration: 3000,
    publishedAt: now - 10 * oneDay,
  },
  {
    _id: 'pt5',
    type: 'podcast_transcript',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'Product Managers Club: Feature Prioritization',
    snippet: 'Transcript from podcast episode about feature prioritization frameworks...',
    tags: ['podcast', 'prioritization', 'frameworks'],
    podcastName: 'Product Managers Club',
    episodeTitle: 'Feature Prioritization Frameworks',
    episodeNumber: 12,
    transcript: 'Learn about RICE, ICE, and other frameworks for prioritizing features...',
    duration: 2400,
    publishedAt: now - 5 * oneDay,
  },

  // ==========================================
  // 🎥 Video Content
  // ==========================================

  // video_transcript
  {
    _id: 'vt1',
    type: 'video_transcript',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'YouTube: Product Roadmap Planning',
    snippet: 'Transcript from YouTube video about planning product roadmaps...',
    tags: ['video', 'youtube', 'roadmap'],
    videoTitle: 'How to Plan a Product Roadmap',
    videoUrl: 'https://youtube.com/watch?v=abc123',
    channel: 'Product Management',
    transcript: 'In this video, we\'ll cover how to create a product roadmap that aligns with business goals...',
    duration: 1200, // seconds
    publishedAt: now - 7 * oneDay,
  },
  {
    _id: 'vt2',
    type: 'video_transcript',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'YouTube: User Interview Techniques',
    snippet: 'Transcript from YouTube video about conducting effective user interviews...',
    tags: ['video', 'youtube', 'interviews'],
    videoTitle: 'User Interview Techniques That Work',
    videoUrl: 'https://youtube.com/watch?v=def456',
    channel: 'UX Research',
    transcript: 'Learn the best techniques for conducting user interviews that yield actionable insights...',
    duration: 900,
    publishedAt: now - 14 * oneDay,
  },
  {
    _id: 'vt3',
    type: 'video_transcript',
    userId: 'user1',
    processed: true,
    processedAt: now - 18 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'YouTube: A/B Testing Guide',
    snippet: 'Transcript from YouTube video about setting up A/B tests...',
    tags: ['video', 'youtube', 'testing'],
    videoTitle: 'A/B Testing Guide for Product Managers',
    videoUrl: 'https://youtube.com/watch?v=ghi789',
    channel: 'Data-Driven PM',
    transcript: 'Complete guide to A/B testing: from hypothesis to analysis...',
    duration: 1500,
    publishedAt: now - 21 * oneDay,
  },
  {
    _id: 'vt4',
    type: 'video_transcript',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'YouTube: Product Metrics Explained',
    snippet: 'Transcript from YouTube video explaining key product metrics...',
    tags: ['video', 'youtube', 'metrics'],
    videoTitle: 'Product Metrics Every PM Should Know',
    videoUrl: 'https://youtube.com/watch?v=jkl012',
    channel: 'Product Analytics',
    transcript: 'Understanding DAU, MAU, retention, and other key product metrics...',
    duration: 1800,
    publishedAt: now - 10 * oneDay,
  },
  {
    _id: 'vt5',
    type: 'video_transcript',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'YouTube: Design System Tutorial',
    snippet: 'Transcript from YouTube video tutorial about building design systems...',
    tags: ['video', 'youtube', 'design'],
    videoTitle: 'Building a Design System from Scratch',
    videoUrl: 'https://youtube.com/watch?v=mno345',
    channel: 'Design Systems',
    transcript: 'Step-by-step tutorial on building a design system that scales...',
    duration: 2100,
    publishedAt: now - 5 * oneDay,
  },

  // ==========================================
  // 📄 Documents
  // ==========================================

  // pdf_document
  {
    _id: 'pdf1',
    type: 'pdf_document',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Product Strategy Document',
    snippet: 'PDF document outlining product strategy for Q1 2024...',
    tags: ['pdf', 'strategy', 'document'],
    fileId: 'file1',
    fileName: 'Product_Strategy_Q1_2024.pdf',
    pageCount: 25,
    extractedText: 'This document outlines our product strategy for Q1 2024, focusing on user engagement and feature development...',
  },
  {
    _id: 'pdf2',
    type: 'pdf_document',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'User Research Report',
    snippet: 'PDF report summarizing user research findings from Q4...',
    tags: ['pdf', 'research', 'report'],
    fileId: 'file2',
    fileName: 'User_Research_Report_Q4.pdf',
    pageCount: 42,
    extractedText: 'This report summarizes our user research findings from Q4, including key insights and recommendations...',
  },
  {
    _id: 'pdf3',
    type: 'pdf_document',
    userId: 'user1',
    processed: true,
    processedAt: now - 12 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Competitor Analysis Report',
    snippet: 'PDF document analyzing competitor products and features...',
    tags: ['pdf', 'competitor', 'analysis'],
    fileId: 'file3',
    fileName: 'Competitor_Analysis_2024.pdf',
    pageCount: 18,
    extractedText: 'Analysis of competitor products, features, and market positioning...',
  },
  {
    _id: 'pdf4',
    type: 'pdf_document',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'API Documentation',
    snippet: 'PDF documentation for product API endpoints and usage...',
    tags: ['pdf', 'api', 'documentation'],
    fileId: 'file4',
    fileName: 'API_Documentation_v2.pdf',
    pageCount: 67,
    extractedText: 'Complete API documentation including endpoints, authentication, and examples...',
  },
  {
    _id: 'pdf5',
    type: 'pdf_document',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'Design System Guidelines',
    snippet: 'PDF document with design system guidelines and component specs...',
    tags: ['pdf', 'design', 'systems'],
    fileId: 'file5',
    fileName: 'Design_System_Guidelines.pdf',
    pageCount: 89,
    extractedText: 'Comprehensive design system guidelines including components, patterns, and best practices...',
  },

  // word_document
  {
    _id: 'wd1',
    type: 'word_document',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Product Requirements Document',
    snippet: 'Word document with product requirements for new feature...',
    tags: ['word', 'prd', 'requirements'],
    fileId: 'file6',
    fileName: 'PRD_Feature_Authentication.docx',
    extractedText: 'Product Requirements Document for new authentication feature...',
  },
  {
    _id: 'wd2',
    type: 'word_document',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'User Story Template',
    snippet: 'Word document template for writing user stories...',
    tags: ['word', 'template', 'user-stories'],
    fileId: 'file7',
    fileName: 'User_Story_Template.docx',
    extractedText: 'Template for writing effective user stories with acceptance criteria...',
  },
  {
    _id: 'wd3',
    type: 'word_document',
    userId: 'user1',
    processed: true,
    processedAt: now - 18 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Meeting Minutes Template',
    snippet: 'Word document template for recording meeting minutes...',
    tags: ['word', 'template', 'meetings'],
    fileId: 'file8',
    fileName: 'Meeting_Minutes_Template.docx',
    extractedText: 'Template for documenting meeting minutes and action items...',
  },
  {
    _id: 'wd4',
    type: 'word_document',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Product Launch Plan',
    snippet: 'Word document outlining product launch plan and timeline...',
    tags: ['word', 'launch', 'plan'],
    fileId: 'file9',
    fileName: 'Product_Launch_Plan.docx',
    extractedText: 'Detailed product launch plan including timeline, milestones, and resources...',
  },
  {
    _id: 'wd5',
    type: 'word_document',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'User Research Guide',
    snippet: 'Word document guide for conducting user research...',
    tags: ['word', 'research', 'guide'],
    fileId: 'file10',
    fileName: 'User_Research_Guide.docx',
    extractedText: 'Comprehensive guide for conducting effective user research...',
  },

  // ==========================================
  // ✍️ Annotations
  // ==========================================

  // annotation
  {
    _id: 'an1',
    type: 'annotation',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Annotation: Product Strategy Document',
    snippet: 'Margin note on product strategy document about user engagement...',
    tags: ['annotation', 'strategy', 'note'],
    annotatedText: 'Focus on user engagement metrics',
    note: 'This is a key metric we should track more closely',
    sourceType: 'pdf_document',
    sourceId: 'pdf1',
    pageNumber: 12,
  },
  {
    _id: 'an2',
    type: 'annotation',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'Annotation: Research Report',
    snippet: 'Highlight and note on user research report about key insight...',
    tags: ['annotation', 'research', 'highlight'],
    annotatedText: 'Users want better mobile experience',
    note: 'Priority: Improve mobile onboarding flow',
    sourceType: 'pdf_document',
    sourceId: 'pdf2',
    pageNumber: 8,
  },
  {
    _id: 'an3',
    type: 'annotation',
    userId: 'user1',
    processed: true,
    processedAt: now - 12 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Annotation: Web Article',
    snippet: 'Note on web article about feature prioritization...',
    tags: ['annotation', 'article', 'note'],
    annotatedText: 'Use RICE framework for prioritization',
    note: 'Good framework to implement in our process',
    sourceType: 'web_article',
    sourceId: 'wa1',
  },
  {
    _id: 'an4',
    type: 'annotation',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Annotation: Book Highlight',
    snippet: 'Margin note on book highlight about product management...',
    tags: ['annotation', 'book', 'highlight'],
    annotatedText: 'The best products solve real user problems',
    note: 'Always validate problem before building solution',
    sourceType: 'readwise_highlight',
    sourceId: 'rw1',
  },
  {
    _id: 'an5',
    type: 'annotation',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'Annotation: Meeting Notes',
    snippet: 'Note added to meeting notes about action item...',
    tags: ['annotation', 'meeting', 'action'],
    annotatedText: 'Schedule user research sessions',
    note: 'Follow up with research team this week',
    sourceType: 'meeting_note',
    sourceId: 'mn1',
  },

  // ==========================================
  // 💬 Communication Platforms
  // ==========================================

  // slack_message
  {
    _id: 'sl1',
    type: 'slack_message',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Slack: Product Update Discussion',
    snippet: 'Slack message thread about upcoming product update...',
    tags: ['slack', 'discussion', 'product'],
    channel: '#product-team',
    author: 'Sarah Chen',
    message: 'We should prioritize the mobile improvements based on user feedback',
    threadId: 'thread1',
    timestamp: now - 1 * oneDay,
  },
  {
    _id: 'sl2',
    type: 'slack_message',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'Slack: User Research Link',
    snippet: 'Slack message sharing link to user research results...',
    tags: ['slack', 'research', 'link'],
    channel: '#research',
    author: 'Mike Johnson',
    message: 'Here are the results from our latest user research session: [link]',
    threadId: null,
    timestamp: now - 2 * oneDay,
  },
  {
    _id: 'sl3',
    type: 'slack_message',
    userId: 'user1',
    processed: true,
    processedAt: now - 18 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Slack: Feature Request',
    snippet: 'Slack message from user requesting new feature...',
    tags: ['slack', 'feature-request', 'user'],
    channel: '#user-feedback',
    author: 'User Support',
    message: 'User requested: "Can we add collaborative editing feature?"',
    threadId: null,
    timestamp: now - 3 * oneDay,
  },
  {
    _id: 'sl4',
    type: 'slack_message',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Slack: Design Review',
    snippet: 'Slack message about design review meeting...',
    tags: ['slack', 'design', 'review'],
    channel: '#design',
    author: 'Emma Davis',
    message: 'Design review scheduled for tomorrow at 2pm. Please review the mockups before then.',
    threadId: null,
    timestamp: now - 4 * oneDay,
  },
  {
    _id: 'sl5',
    type: 'slack_message',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'Slack: Sprint Planning',
    snippet: 'Slack message about sprint planning agenda...',
    tags: ['slack', 'sprint', 'planning'],
    channel: '#engineering',
    author: 'John Doe',
    message: 'Sprint planning agenda: 1) Review backlog 2) Prioritize features 3) Assign tasks',
    threadId: null,
    timestamp: now - 5 * oneDay,
  },

  // ==========================================
  // 📅 Calendar & Events
  // ==========================================

  // calendar_event_note
  {
    _id: 'ce1',
    type: 'calendar_event_note',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Meeting Notes: Product Review',
    snippet: 'Notes from calendar event: Product Review meeting...',
    tags: ['calendar', 'meeting', 'notes'],
    eventTitle: 'Product Review Meeting',
    eventDate: now - 1 * oneDay,
    attendees: ['Product Team', 'Leadership'],
    notes: 'Discussed Q4 performance and Q1 roadmap. Key decision: Focus on user engagement.',
  },
  {
    _id: 'ce2',
    type: 'calendar_event_note',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'Meeting Notes: User Research Session',
    snippet: 'Notes from calendar event: User Research Session...',
    tags: ['calendar', 'research', 'user'],
    eventTitle: 'User Research Session',
    eventDate: now - 2 * oneDay,
    attendees: ['Research Team', 'Product Team'],
    notes: 'Conducted user interviews. Key insight: Users want better mobile experience.',
  },
  {
    _id: 'ce3',
    type: 'calendar_event_note',
    userId: 'user1',
    processed: true,
    processedAt: now - 12 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Meeting Notes: Design Critique',
    snippet: 'Notes from calendar event: Design Critique session...',
    tags: ['calendar', 'design', 'critique'],
    eventTitle: 'Design Critique Session',
    eventDate: now - 3 * oneDay,
    attendees: ['Design Team'],
    notes: 'Reviewed new feature mockups. Feedback: Improve mobile navigation.',
  },
  {
    _id: 'ce4',
    type: 'calendar_event_note',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Meeting Notes: Sprint Planning',
    snippet: 'Notes from calendar event: Sprint Planning meeting...',
    tags: ['calendar', 'sprint', 'planning'],
    eventTitle: 'Sprint Planning',
    eventDate: now - 4 * oneDay,
    attendees: ['Development Team'],
    notes: 'Planned next sprint. Focus: User authentication improvements.',
  },
  {
    _id: 'ce5',
    type: 'calendar_event_note',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'Meeting Notes: Retrospective',
    snippet: 'Notes from calendar event: Sprint Retrospective...',
    tags: ['calendar', 'retrospective', 'sprint'],
    eventTitle: 'Sprint Retrospective',
    eventDate: now - 5 * oneDay,
    attendees: ['Development Team'],
    notes: 'What went well: Communication. What to improve: Code review process.',
  },

  // ==========================================
  // ✓ Checklists & Tasks
  // ==========================================

  // checklist
  {
    _id: 'cl1',
    type: 'checklist',
    userId: 'user1',
    processed: false,
    createdAt: now - 1 * oneDay,
    title: 'Product Launch Checklist',
    snippet: 'Checklist for product launch preparation and tasks...',
    tags: ['checklist', 'launch', 'tasks'],
    items: [
      { text: 'Complete user testing', completed: true },
      { text: 'Finalize marketing materials', completed: false },
      { text: 'Prepare support documentation', completed: false },
      { text: 'Schedule launch announcement', completed: false },
    ],
  },
  {
    _id: 'cl2',
    type: 'checklist',
    userId: 'user1',
    processed: false,
    createdAt: now - 2 * oneDay,
    title: 'User Research Preparation',
    snippet: 'Checklist for preparing user research sessions...',
    tags: ['checklist', 'research', 'preparation'],
    items: [
      { text: 'Prepare interview questions', completed: true },
      { text: 'Schedule participants', completed: true },
      { text: 'Set up recording equipment', completed: false },
      { text: 'Review previous research notes', completed: false },
    ],
  },
  {
    _id: 'cl3',
    type: 'checklist',
    userId: 'user1',
    processed: true,
    processedAt: now - 18 * 60 * 60 * 1000,
    createdAt: now - 3 * oneDay,
    title: 'Feature Development Tasks',
    snippet: 'Checklist for new feature development tasks...',
    tags: ['checklist', 'feature', 'development'],
    items: [
      { text: 'Write PRD', completed: true },
      { text: 'Design mockups', completed: true },
      { text: 'Implement feature', completed: false },
      { text: 'Write tests', completed: false },
      { text: 'Deploy to staging', completed: false },
    ],
  },
  {
    _id: 'cl4',
    type: 'checklist',
    userId: 'user1',
    processed: false,
    createdAt: now - 4 * oneDay,
    title: 'Design System Update Tasks',
    snippet: 'Checklist for updating design system components...',
    tags: ['checklist', 'design', 'systems'],
    items: [
      { text: 'Update button component', completed: true },
      { text: 'Add new color tokens', completed: false },
      { text: 'Update documentation', completed: false },
      { text: 'Share with team', completed: false },
    ],
  },
  {
    _id: 'cl5',
    type: 'checklist',
    userId: 'user1',
    processed: false,
    createdAt: now - 5 * oneDay,
    title: 'Q1 Planning Checklist',
    snippet: 'Checklist for Q1 planning and goal setting...',
    tags: ['checklist', 'planning', 'q1'],
    items: [
      { text: 'Review Q4 performance', completed: true },
      { text: 'Set Q1 goals', completed: false },
      { text: 'Create roadmap', completed: false },
      { text: 'Align with stakeholders', completed: false },
    ],
  },
];

// Helper function to get all items of a specific type
export function getItemsByType(type: InputSourceType): MockInboxItem[] {
  return mockBrainInputs.filter((item) => item.type === type);
}

// Helper function to get all unprocessed items
export function getUnprocessedItems(): MockInboxItem[] {
  return mockBrainInputs.filter((item) => !item.processed);
}

// Helper function to get all processed items
export function getProcessedItems(): MockInboxItem[] {
  return mockBrainInputs.filter((item) => item.processed);
}

// Helper function to get items by tag
export function getItemsByTag(tag: string): MockInboxItem[] {
  return mockBrainInputs.filter((item) => item.tags.includes(tag));
}

